## 项目配置文件模板
server:
  port: 8088
  servlet:
    context-path: /graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graceful-coding?useSSL=false&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: root
